### PR TITLE
Support Translations / Generate PDF Output for Translations

### PR DESCRIPTION
**Pull request by wombelix**
Based on Branch "migrate", shouldn't therefore be merged before PR #1 was reviewed and completed.

Small adjustment to include Translations as well during PDF Generation, so far only Articles and Pages in the Default Language were recognized.

### CODE REVIEW

**Comment by justinmayer** [comment]
Looks good. Could you drop the four commits related to the other PR and rebase 0f52e85cbb6912c7d1a02b57beade8fc9f9830bb onto current `main`?

**Comment by wombelix** [comment]
Thank you, sure thing, i merged from https://github.com/pelican-plugins/pdf/commit/f6aadba541e48add51a5cbf629ff8f1c8f98b3b7 but for my understanding the result is what you were asking for, see: https://github.com/wombelix/pdf/commit/9d404019e473a6628a385a966824707888ce8bb8

**Comment by justinmayer** [comment]
Many thanks for the enhancement, Dominik. Merged via https://github.com/pelican-plugins/pdf/commit/a8bc3a210fd2368be227b6d2e6f6558c5023e346.

**Comment by justinmayer** [comment]
Thanks again for all your efforts on this plugin, Dominik! Your work up until this point (before the intra-site link syntax support) has been published to PyPI as PDF Generator 1.0. 🎉

**Pull request closed without merging**
